/******************************************************************************
* coffee.sql
*
* Team Members:
*   Kirtis Hubbard (PM)  - Project management, documentation, indexes, evaluate & synthesize query
*   Christian Doolittle  - Database design, table creation, subquery, data population
*   Aadesh Kumar         - Stored procedure, stored function, updatable view, backup/restore
*
* Business Description:
*   This database models a coffee bean wholesale company that sources beans
*   from farms around the world and sells them to local coffee shops in the
*   Kirkland and Redmond, WA area. The database tracks farm suppliers, coffee
*   flavors, product inventory, client coffee shops, and their orders.
*
* Data Sources:
*   - Farm names and addresses: Generated by ChatGPT (fictional)
*   - Coffee shop names and addresses: Real businesses in Kirkland/Redmond, WA
*     sourced from Google Maps
******************************************************************************/

/*** MIDTERM PROJECT SECTION *************************************************/

drop database if exists coffee;
create database coffee;
use coffee;

/*** Create tables ***********************************************************/

-- The farms we source our coffee from.
create table farms (
       farm_id   int          not null auto_increment
     , farm_name varchar(64)  not null
     , address   varchar(256) not null
     , country   varchar(32)  not null
     , constraint pk_farms           primary key (farm_id)
     , constraint uq_farms_farm_name unique (farm_name)
);

-- The types of coffee we sell.
create table flavors (
       flavor_id    int          not null auto_increment
     , flavor_name  varchar(32)  not null
     , price_per_lb decimal(5,2) not null
     , constraint pk_flavors             primary key (flavor_id)
     , constraint uq_flavors_flavor_name unique (flavor_name)
);

-- How much of each type of coffee we have in stock. This should be read by an
-- intermediate service to determine whether orders can be made on our
-- frontend.
-- Each item in this list represents stock of a given flavor from a given farm.
create table inventory (
       inventory_id  int           not null auto_increment
     , flavor_id     int           not null
     , farm_id       int           not null
     , lbs_available decimal(10,2) not null
     , constraint pk_inventory         primary key (inventory_id)
     , constraint fk_inventory_flavors foreign key (flavor_id) references flavors (flavor_id)
     , constraint fk_inventory_farms   foreign key (farm_id)   references farms   (farm_id)
     , constraint uq_inventory         unique (flavor_id, farm_id)
);

-- The actual items to be listed on our frontend.
-- Each item is just a flavor with a weight - we're selling bags of beans.
create table products (
       product_id  int          not null auto_increment
     , item_weight decimal(4,2) not null
     , flavor_id   int          not null
     , constraint pk_products         primary key (product_id)
     , constraint fk_products_flavors foreign key (flavor_id) references flavors (flavor_id)
);

-- I couldn't auto-generate a readable product_name, so I made a view for it
create view vw_products_readable as
select product_id
     , concat(flavor_name, ' (', item_weight, 'lbs)') as product_name
     , item_weight
     , products.flavor_id
  from products
  join flavors on flavors.flavor_id = products.flavor_id
;

-- Stores (coffee shops) that have bought our product.
create table clients (
       client_id    int          not null auto_increment
     , client_name  varchar(64)  not null
     , ship_address varchar(256) not null
     , constraint pk_clients              primary key (client_id)
     , constraint uq_clients_client_name  unique (client_name)
     , constraint uq_clients_ship_address unique (ship_address)
);

-- All orders, fulfilled and unfulfilled.
create table orders (
       order_id    int           not null auto_increment
     , order_date  datetime      not null
     , ship_date   datetime
     , received    boolean       not null default false
     , amount      decimal(10,2) not null
     , tax_percent decimal(5,2)
     , item_count  int           not null default 1
     , client_id   int           not null
     , product_id  int           not null
     , constraint pk_orders          primary key (order_id)
     , constraint fk_orders_clients  foreign key (client_id)  references clients  (client_id)
     , constraint fk_orders_products foreign key (product_id) references products (product_id)
     , constraint ck_orders_dates              check (ship_date is null or order_date < ship_date)
     , constraint ck_orders_received_ship_date check (not (received and ship_date is null))
);

/*** Insert static data ******************************************************/

-- Fake farm names and addresses generated by ChatGPT
insert into farms (farm_name, country, address)
values ('Fazenda Sol do Cerrado'       , 'Brazil'   , 'Rodovia MG-188, Km 42, Zona Rural, Patrocínio, Minas Gerais, Brazil, 38740-000')
     , ('Santa Aurora Coffee Estate'   , 'Brazil'   , 'Estrada da Serra Azul, s/n, Distrito de São Pedro, Carmo de Minas, Minas Gerais, Brazil, 37472-000')
     , ('Vale Verde do Sul Café'       , 'Brazil'   , 'Linha Boa Esperança, 2150, Interior, Venda Nova do Imigrante, Espírito Santo, Brazil, 29375-000')
     , ('Abeba Highlands Coffee Garden', 'Ethiopia' , 'Kebele 04, Gedeb Road, Gedeo Zone, Yirgacheffe, Ethiopia, 00100')
     , ('Finca Sierra de Bruma'        , 'Cuba'     , 'Camino El Naranjal, Km 6, Sierra Maestra, Buey Arriba, Granma Province, Cuba')
     , ('Kilimani Ridge Cooperative'   , 'Kenya'    , 'Kiambu County, Gatundu South, Kenya')
     , ('Sumatra Highlands Mill'       , 'Indonesia', 'Lintong Nihuta, Humbang Hasundutan, North Sumatra, Indonesia')
     , ('Antigua Valley Estate'        , 'Guatemala', 'Antigua Guatemala, Sacatepéquez, Guatemala')
     , ('Blue Mountain Terrace'        , 'Jamaica'  , 'Portland Parish, Blue Mountains, Jamaica')
     , ('Huehuetenango Cloud Farm'     , 'Guatemala', 'La Democracia, Huehuetenango, Guatemala')
;

-- Real coffee shops in Kirkland and Redmond
insert into clients (client_name, ship_address)
values ('5 Stones Coffee Co.'             , '8102 161st Avenue Northeast, Redmond, WA 98052')
     , ('Rose Hill Café'                  , '12633 NE 85th St, Kirkland, WA 98033'          )
     , ('Downpour Coffee and Sandwich Bar', '13200 Old Redmond Rd #150, Redmond, WA 98052'  )
     , ('Kirkland Roasters'               , '11720 100th Ave NE, Kirkland, WA 98034'        )
     , ('Redmond Bean Lab'                , '16705 Redmond Way, Redmond, WA 98052'          )
     , ('Totem Lake Espresso'             , '12520 120th Ave NE, Kirkland, WA 98034'        )
     , ('Lakeview Coffee Stand'           , '15 Lake St S, Kirkland, WA 98033'              )
     , ('Cedar Park Café'                 , '12300 NE 8th St, Bellevue, WA 98005'           )
     , ('Downtown Pourhouse'              , '7525 166th Ave NE, Redmond, WA 98052'          )
     , ('Union Hill Coffee'               , '21405 NE Union Hill Rd, Redmond, WA 98053'     )
;

-- Made up by Christian and Aadesh
insert into flavors (price_per_lb, flavor_name)
values ( 8.99, 'Original Roast'  )
     , ( 9.49, 'Light Roast'     )
     , (11.99, 'Arabian Blend'   )
     , (10.99, 'Cuban Dark Roast')
     , (12.49, 'Kenyan Bright'   )
     , (11.49, 'Sumatra Earthy'  )
     , (10.49, 'Guatemala Cocoa' )
     , (13.99, 'Blue Mountain'   )
     , ( 9.99, 'Morning Decaf'   )
     , (12.99, 'Holiday Spice'   )
;

/*** Insert example state data ***********************************************/

insert into products (flavor_id, item_weight)
values ( 1,  1.00)
     , ( 1,  2.00)
     , ( 1,  5.00)
     , ( 1, 10.00)
     , ( 2,  2.00)
     , ( 2,  5.00)
     , ( 2, 10.00)
     , ( 3,  1.00)
     , ( 3,  5.00)
     , ( 3, 10.00)
     , ( 4,  5.00)
     , ( 5,  1.00)
     , ( 5,  2.00)
     , ( 5,  5.00)
     , ( 6,  1.00)
     , ( 6,  2.00)
     , ( 6,  5.00)
     , ( 7,  1.00)
     , ( 7,  2.00)
     , ( 7,  5.00)
     , ( 8,  1.00)
     , ( 8,  2.00)
     , ( 8,  5.00)
     , ( 9,  1.00)
     , ( 9,  2.00)
     , ( 9,  5.00)
     , (10,  1.00)
     , (10,  2.00)
     , (10,  5.00)
;

insert into inventory (flavor_id, farm_id, lbs_available)
values (1 , 1 , 250.00)
     , (1 , 2 , 180.00)
     , (2 , 3 , 140.00)
     , (3 , 4 , 120.00)
     , (4 , 5 ,  90.00)
     , (5 , 6 , 110.00)
     , (6 , 7 , 160.00)
     , (7 , 8 , 130.00)
     , (8 , 9 ,  75.00)
     , (9 , 1 , 200.00)
     , (10, 2 ,  95.00)
     , (7 , 10, 105.00)
;

insert into orders (order_date, ship_date, received, amount, tax_percent, item_count, client_id, product_id)
values ('2026-01-10 10:00:00', '2026-01-12 10:00:00', true , 17.98, 9.50, 2,  1,  1)
     , ('2026-01-11 11:30:00', '2026-01-13 11:30:00', true , 47.45, 9.50, 5,  2,  5)
     , ('2026-01-12 09:15:00', '2026-01-14 09:15:00', false, 59.95, 9.50, 5,  3,  9)
     , ('2026-01-13 14:20:00', '2026-01-16 14:20:00', true , 54.95, 9.50, 5,  4, 11)
     , ('2026-01-14 08:05:00', '2026-01-16 08:05:00', false, 24.98, 9.50, 2,  5, 12)
     , ('2026-01-15 12:45:00', '2026-01-18 12:45:00', true , 22.98, 9.50, 2,  6, 15)
     , ('2026-01-16 16:10:00', '2026-01-19 16:10:00', false, 20.98, 9.50, 2,  7, 18)
     , ('2026-01-17 10:55:00', '2026-01-20 10:55:00', true , 27.98, 9.50, 2,  8, 21)
     , ('2026-01-18 09:40:00', '2026-01-21 09:40:00', false, 19.98, 9.50, 2,  9, 24)
     , ('2026-01-19 13:25:00', '2026-01-22 13:25:00', true , 25.98, 9.50, 2, 10, 27)
;

-- Addresses midterm feedback: this insert uses DEFAULT values for received (false) and item_count (1)
insert into orders (order_date, ship_date, amount, tax_percent, client_id, product_id)
values ('2026-01-20 15:00:00', null, 12.49, 9.50, 1, 12)
;

/*** Display finished tables *************************************************/

select count(*) from farms;
select * from farms;

select count(*) from flavors;
select * from flavors;

select count(*) from products;
select * from products;

select count(*) from clients;
select * from clients;

select count(*) from inventory;
select * from inventory;

select count(*) from orders;
select * from orders;

/*** FINAL PROJECT SECTION ***************************************************/

/*** Programming Problem - Indexes *******************************************/
-- Indexes on join conditions and WHERE clause columns used in final project queries

-- Join condition: orders.client_id used in subquery and stored procedure
create index idx_orders_client_id
    on orders (client_id);

-- WHERE condition: flavors.price_per_lb used in updatable view
create index idx_flavors_price_per_lb
    on flavors (price_per_lb);

-- WHERE condition: orders.received used in stored procedure
create index idx_orders_received
    on orders (received);

/*** Programming Problem - Subquery ******************************************/

-- Get orders from Downpour without knowing client_id
select *
  from orders
 where client_id = (
         select client_id
           from clients
          where client_name = 'Downpour Coffee and Sandwich Bar'
       )
;

/*** Programming Problem - Updatable Single Table View ***********************/

create or replace view vw_premium_flavors as
select flavor_id
     , flavor_name
     , price_per_lb
  from flavors
 where price_per_lb >= 10
;

-- Step 1: Query the view
select * from vw_premium_flavors;

-- Step 2: Update a record that satisfies the WHERE clause
set sql_safe_updates = 0;
update vw_premium_flavors
   set price_per_lb = 13.49
 where flavor_name = 'Kenyan Bright'
;
set sql_safe_updates = 1;

-- Step 3: Re-query to confirm the update
select * from vw_premium_flavors;

/*** Programming Problem - Stored Procedure **********************************/

drop procedure if exists sp_calculate_client_revenue;

delimiter //

create procedure sp_calculate_client_revenue()
begin
    declare v_client_name varchar(64);
    declare v_revenue decimal(10,2);
    declare v_total_revenue decimal(10,2) default 0.00;
    declare v_result text default '';
    declare v_tier varchar(20);
    declare v_done int default false;

    declare revenue_cursor cursor for
        select c.client_name, sum(o.amount) as revenue
          from clients c
          join orders o on c.client_id = o.client_id
         where o.received = true
         group by c.client_name
         order by revenue desc;

    declare continue handler for not found set v_done = true;

    open revenue_cursor;

    read_loop: loop
        fetch revenue_cursor into v_client_name, v_revenue;
        if v_done then
            leave read_loop;
        end if;

        set v_total_revenue = v_total_revenue + v_revenue;

        if v_revenue >= 40 then
            set v_tier = 'High Value';
        else
            set v_tier = 'Standard';
        end if;

        if v_result != '' then
            set v_result = concat(v_result, ' | ');
        end if;
        set v_result = concat(v_result, v_client_name, ': $', v_revenue, ' (', v_tier, ')');
    end loop;

    close revenue_cursor;

    select v_result as client_revenue_breakdown;
    select concat('Total revenue from received orders: $', v_total_revenue) as total_revenue;
end //

delimiter ;

call sp_calculate_client_revenue();

/*** Programming Problem - Stored Function ***********************************/

drop function if exists fn_calculate_order_total;

delimiter //

create function fn_calculate_order_total(p_order_id int)
returns decimal(10,2)
deterministic
reads sql data
begin
    declare v_amount decimal(10,2);
    declare v_tax_percent decimal(5,2);
    declare v_total decimal(10,2);

    select amount, tax_percent
      into v_amount, v_tax_percent
      from orders
     where order_id = p_order_id;

    if v_tax_percent is null then
        set v_total = v_amount;
    else
        set v_total = v_amount + round(v_amount * v_tax_percent / 100, 2);
    end if;

    return v_total;
end //

delimiter ;

select order_id, fn_calculate_order_total(order_id) as order_total
  from orders;

/*** Programming Problem - Evaluate and Synthesize ***************************/

/*
Business Scenario:
You've been hired as a data analyst for a company with multiple departments across two regions. 
Leadership wants to evaluate which departments are offering competitive salaries and identify areas where compensation strategies may need adjustment.

Analytical Task:
Write a SQL query that joins the Employee, Department, and Region tables to calculate the average salary for each department and region. Use GROUP BY with ROLLUP to include department-level, region-level, and overall averages. Filter out any group whose average salary is less than or equal to $65,000.

Presentation Requirements:
- Include only employees earning more than $60,000
- Use GROUP BY with ROLLUP to show department, region, and overall averages
- Use HAVING to exclude low-paying groups (≤ $65,000)
- Round average salary to two decimal places
- Order results by region and department name, with detail rows first, followed by subtotals and grand total

Business Goal:
Help leadership pinpoint which departments and regions are offering high salaries, and highlight areas that may require strategic compensation review.

The ResultSet you should get from the query to be written is:
region_name     department_name     avg_salary
North           HR                  73000.00
North           Sales               74000.00
North           NULL                73500.00
South           Finance             76666.67
South           IT                  80333.33
South           NULL                78500.00
NULL            NULL                76000.00
*/

-- Create and use the database
DROP DATABASE IF EXISTS BusinessAnalytics;
CREATE DATABASE BusinessAnalytics;
USE BusinessAnalytics;

-- Hierarchical Tables
CREATE TABLE Region (
    region_id INT AUTO_INCREMENT,
    region_name VARCHAR(50),
    CONSTRAINT PK_Region PRIMARY KEY (region_id)
);

CREATE TABLE Department (
    department_id INT AUTO_INCREMENT,
    department_name VARCHAR(50),
    region_id INT,
    CONSTRAINT PK_Department PRIMARY KEY (department_id),
    CONSTRAINT FK_Department_Region FOREIGN KEY (region_id) REFERENCES Region(region_id)
);

CREATE TABLE Employee (
    employee_id INT AUTO_INCREMENT,
    employee_name VARCHAR(50),
    department_id INT,
    salary DECIMAL(10,2),
    CONSTRAINT PK_Employee PRIMARY KEY (employee_id),
    CONSTRAINT FK_Employee_Department FOREIGN KEY (department_id) REFERENCES Department(department_id)
);

-- Insert data into Region
INSERT INTO Region (region_name) VALUES ('North'), ('South');

-- Insert data into Department
INSERT INTO Department (department_name, region_id) VALUES 
  ('HR', 1), ('Sales', 1), ('IT', 2), ('Finance', 2);

INSERT INTO Employee (employee_name, department_id, salary) VALUES
  -- HR Department (ID 1, Region 1)
  ('Alice', 1, 60000),
  ('Bob', 1, 71000),
  ('Clara', 1, 73000),
  ('David', 1, 75000),

  -- Sales Department (ID 2, Region 1)
  ('Ethan', 2, 72000),
  ('Fiona', 2, 74000),
  ('George', 2, 76000),

  -- IT Department (ID 3, Region 2)
  ('Hannah', 3, 80000),
  ('Ian', 3, 82000),
  ('Julia', 3, 79000),

  -- Finance Department (ID 4, Region 2)
  ('Kevin', 4, 75000),
  ('Laura', 4, 77000),
  ('Mason', 4, 78000);

-- disable ONLY_FULL_GROUP_BY mode, which is the default, to get the below to work
SET SESSION sql_mode = (SELECT REPLACE(@@SESSION.sql_mode, 'ONLY_FULL_GROUP_BY', ''));

-- Example of a Analytical Query with ROLLUP
CREATE OR REPLACE VIEW vw_avg_salary_by_region_department AS
SELECT 
    r.region_name,
    d.department_name,
    ROUND(AVG(e.salary), 2) AS avg_salary
FROM 
    Employee e
    JOIN Department d ON e.department_id = d.department_id
    JOIN Region r ON d.region_id = r.region_id
WHERE 
    e.salary > 60000
GROUP BY 
    r.region_name, d.department_name WITH ROLLUP
HAVING 
    AVG(e.salary) > 65000
ORDER BY 
  CASE WHEN r.region_name IS NULL THEN 2
       WHEN d.department_name IS NULL THEN 1
       ELSE 0 END,
  r.region_name,
  d.department_name;

-- Select from the view
SELECT * FROM vw_avg_salary_by_region_department;

/*
Business Scenario:
You've been hired as a data analyst for a retail company specializing in electronics and furniture. Leadership wants to identify which product groups are generating strong revenue from high-priced items to guide future pricing and inventory strategies.

Analytical Task:
Write a SQL query that joins the Item, Subcategory, and Category tables to calculate total revenue from items priced above $250. Use GROUP BY with ROLLUP to include subtotals by category and subcategory, as well as a grand total. Filter out any group whose total revenue is less than or equal to $1000.

Presentation Requirements:
- Include only items priced above $250
- Use GROUP BY with ROLLUP to show subtotals and grand total
- Use HAVING to exclude low-revenue groups (≤ $1000)
- Order results by category and subcategory name

Business Goal:
Help leadership pinpoint which subcategories and categories are driving significant revenue from 
high-priced items, and highlight areas that may need strategic attention.

The ResultSet you should get from the query to be written is:
category_name		subcategory_name	total_price
Electronics			Laptops				2399.98
Electronics			Phones				1899.98
Electronics			NULL				4299.96
NULL				NULL				5099.94
*/

-- Hierarchical Tables
CREATE TABLE Category (
    category_id INT AUTO_INCREMENT,
    category_name VARCHAR(50),
    CONSTRAINT PK_Category PRIMARY KEY (category_id)
);

CREATE TABLE Subcategory (
    subcategory_id INT AUTO_INCREMENT,
    subcategory_name VARCHAR(50),
    category_id INT,
    CONSTRAINT PK_Subcategory PRIMARY KEY (subcategory_id),
    CONSTRAINT FK_Subcategory_Category FOREIGN KEY (category_id) REFERENCES Category(category_id)
);

CREATE TABLE Item (
    item_id INT AUTO_INCREMENT,
    item_name VARCHAR(50),
    subcategory_id INT,
    price DECIMAL(10,2),
    CONSTRAINT PK_Item PRIMARY KEY (item_id),
    CONSTRAINT FK_Item_Subcategory FOREIGN KEY (subcategory_id) REFERENCES Subcategory(subcategory_id)
);

-- Insert data into Category
INSERT INTO Category (category_name) VALUES ('Electronics'), ('Furniture');

-- Insert data into Subcategory
INSERT INTO Subcategory (subcategory_name, category_id) VALUES 
  ('Phones', 1), ('Laptops', 1), ('Chairs', 2), ('Tables', 2);

-- Insert data into Item
INSERT INTO Item (item_name, subcategory_id, price) VALUES
  ('iPhone', 1, 999.99), ('Galaxy', 1, 899.99), ('MacBook', 2, 1299.99),
  ('Dell', 2, 1099.99), ('Office Chair', 3, 199.99), ('Gaming Chair', 3, 249.99),
  ('Dining Table', 4, 499.99), ('Coffee Table', 4, 299.99);

/*
Goal: Write Analytical query to answer this question:
"Which subcategories and categories are generating significant revenue from high-priced items?"
*/

-- Analytical Query with ROLLUP
CREATE OR REPLACE VIEW vw_total_price_by_category_subcategory AS
SELECT 
    c.category_name,
    s.subcategory_name,
    ROUND(SUM(i.price), 2) AS total_price
FROM 
    Item i
    JOIN Subcategory s ON i.subcategory_id = s.subcategory_id
    JOIN Category c ON s.category_id = c.category_id
WHERE 
    i.price > 250
GROUP BY 
    c.category_name, s.subcategory_name WITH ROLLUP
HAVING 
    SUM(i.price) > 1000
ORDER BY 
    CASE WHEN c.category_name IS NULL THEN 2
         WHEN s.subcategory_name IS NULL THEN 1
         ELSE 0 END,
    c.category_name,
    s.subcategory_name;

-- Select from the view
SELECT * FROM vw_total_price_by_category_subcategory;

-- re-enable ONLY_FULL_GROUP_BY mode to get back to the default
SET SESSION sql_mode = CONCAT_WS(',', @@SESSION.sql_mode, 'ONLY_FULL_GROUP_BY');